### ISSUE TITLE
As a student, I want to enroll in a course

### ISSUE THREAD

**Issue by itsfourthidiot** [itsfourthidiot/ira#14]
Backend:
- There will be an enrollments table having the following attributes: course_id, student_id, enrolled_on.
- GET API to check the enrollment status of student_id across course_id.
- POST API to enroll student_id across course_id.

**Comment by prasadhbk222** [comment]
Firstly check enrollment status by a GET request using student id and course id as parameter. If not enrolled, send a POST request to add a entry to enrollment table. On receiving success response, take the user to its own dashboard.
