### ISSUE TITLE
As an Instructor, I want to create a course.

### ISSUE THREAD

**Issue by prasadhbk222** [itsfourthidiot/ira#33]
Frontend:

- On instructor dashboard, add a button to create new course.
- On click, modal should pop up containing input for title and create/cancel button. 
- On creation, we should be redirected to courses details page which contains left panel.
- Left panel should include course description, course curriculum and additional details. Instructor should be able to save draft or publish course in the end.

**Comment by itsfourthidiot** [comment]
Backend:

- Course model will have the following attributes: id, title, description, date_created, date_published, is_published.
- For course creation, the frontend will send a POST request with the title as a JSON object.

**Comment by itsfourthidiot** [comment]
Backend API to create a course is done
